name: Check Roblox Badge

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: pip install -r requirements.txt
      - run: python checker.py
